services:
  example-frontend:
    image: example-frontend
    build: 
      context: ../material-applications/example-frontend
      dockerfile: Dockerfile
    depends_on:
      - example-backend
  example-backend:
    image: example-backend
    build: 
      context: ../material-applications/example-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:8.0.3-alpine3.21
    restart: always
  postgres:
    image: postgres:14.18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - example-frontend


volumes:
  database: