services:
  simple-web-service-server:
    image: devopsdockeruh/simple-web-service:alpine
    build: .
    command: server
    ports:
      - 8080:8080
    volumes:
      - ./text.log:/usr/src/app/text.log
